
package com.viettel.webservice.voffice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Vo2AutoSignSystemImpl", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Vo2AutoSignSystemImpl {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg7
     * @param arg6
     * @return
     *     returns com.viettel.webservice.voffice.ResultDocument
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchDocument", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.SearchDocument")
    @ResponseWrapper(localName = "searchDocumentResponse", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.SearchDocumentResponse")
    @Action(input = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/searchDocumentRequest", output = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/searchDocumentResponse")
    public ResultDocument searchDocument(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Integer arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        Integer arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        EntityDocument arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        Long arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        Long arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        Boolean arg7);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Long
     */
    @WebMethod(operationName = "Vo2RegDigitalDocByEmail")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Vo2RegDigitalDocByEmail", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.Vo2RegDigitalDocByEmail")
    @ResponseWrapper(localName = "Vo2RegDigitalDocByEmailResponse", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.Vo2RegDigitalDocByEmailResponse")
    @Action(input = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/Vo2RegDigitalDocByEmailRequest", output = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/Vo2RegDigitalDocByEmailResponse")
    public Long vo2RegDigitalDocByEmail(
        @WebParam(name = "arg0", targetNamespace = "")
        KttsVofficeCommInpuParam arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.viettel.webservice.voffice.ResultDocument
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocumentDetail", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.GetDocumentDetail")
    @ResponseWrapper(localName = "getDocumentDetailResponse", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.GetDocumentDetailResponse")
    @Action(input = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/getDocumentDetailRequest", output = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/getDocumentDetailResponse")
    public ResultDocument getDocumentDetail(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.viettel.webservice.voffice.FileAttachTranferList
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFile", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.GetFile")
    @ResponseWrapper(localName = "getFileResponse", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.GetFileResponse")
    @Action(input = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/getFileRequest", output = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/getFileResponse")
    public FileAttachTranferList getFile(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Boolean arg2);

    /**
     * 
     * @param appCode
     * @param tranCode
     * @return
     *     returns com.viettel.webservice.voffice.SignatureImageObjList
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListSignImage", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.GetListSignImage")
    @ResponseWrapper(localName = "getListSignImageResponse", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.GetListSignImageResponse")
    @Action(input = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/getListSignImageRequest", output = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/getListSignImageResponse")
    public SignatureImageObjList getListSignImage(
        @WebParam(name = "appCode", targetNamespace = "")
        String appCode,
        @WebParam(name = "tranCode", targetNamespace = "")
        String tranCode);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "regDigitalDoc", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.RegDigitalDoc")
    @ResponseWrapper(localName = "regDigitalDocResponse", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.RegDigitalDocResponse")
    @Action(input = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/regDigitalDocRequest", output = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/regDigitalDocResponse")
    public Long regDigitalDoc(
        @WebParam(name = "arg0", targetNamespace = "")
        KttsVofficeCommInpuParam arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnMuiltDocResult", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.ReturnMuiltDocResult")
    @ResponseWrapper(localName = "returnMuiltDocResultResponse", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.ReturnMuiltDocResultResponse")
    @Action(input = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/returnMuiltDocResultRequest", output = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/returnMuiltDocResultResponse")
    public Long returnMuiltDocResult(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recallReturnMuiltDocResult", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.RecallReturnMuiltDocResult")
    @ResponseWrapper(localName = "recallReturnMuiltDocResultResponse", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.RecallReturnMuiltDocResultResponse")
    @Action(input = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/recallReturnMuiltDocResultRequest", output = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/recallReturnMuiltDocResultResponse")
    public Long recallReturnMuiltDocResult(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @return
     *     returns com.viettel.webservice.voffice.ResultFieldDocument
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListFieldForDocument", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.GetListFieldForDocument")
    @ResponseWrapper(localName = "getListFieldForDocumentResponse", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.GetListFieldForDocumentResponse")
    @Action(input = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/getListFieldForDocumentRequest", output = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/getListFieldForDocumentResponse")
    public ResultFieldDocument getListFieldForDocument();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authenticate", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.Authenticate")
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.AuthenticateResponse")
    @Action(input = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/authenticateRequest", output = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/authenticateResponse")
    public Long authenticate(
        @WebParam(name = "arg0", targetNamespace = "")
        VofficeCommInpuParam arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns com.viettel.webservice.voffice.TreeParam
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTree", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.GetTree")
    @ResponseWrapper(localName = "getTreeResponse", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.GetTreeResponse")
    @Action(input = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/getTreeRequest", output = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/getTreeResponse")
    public TreeParam getTree(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Long arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "getResponseResult", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.GetResponseResult")
    @ResponseWrapper(localName = "getResponseResultResponse", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.GetResponseResultResponse")
    @Action(input = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/getResponseResultRequest", output = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/getResponseResultResponse")
    public void getResponseResult(
        @WebParam(name = "arg0", targetNamespace = "")
        RrParam arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelTransaction", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.CancelTransaction")
    @ResponseWrapper(localName = "cancelTransactionResponse", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.CancelTransactionResponse")
    @Action(input = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/cancelTransactionRequest", output = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/cancelTransactionResponse")
    public int cancelTransaction(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.viettel.webservice.voffice.RrEmailParam
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInformationStaff", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.GetInformationStaff")
    @ResponseWrapper(localName = "getInformationStaffResponse", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.GetInformationStaffResponse")
    @Action(input = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/getInformationStaffRequest", output = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/getInformationStaffResponse")
    public RrEmailParam getInformationStaff(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkAccount", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.CheckAccount")
    @ResponseWrapper(localName = "checkAccountResponse", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.CheckAccountResponse")
    @Action(input = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/checkAccountRequest", output = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/checkAccountResponse")
    public Long checkAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.viettel.webservice.voffice.TreeParam
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStaffGroup", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.GetStaffGroup")
    @ResponseWrapper(localName = "getStaffGroupResponse", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.GetStaffGroupResponse")
    @Action(input = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/getStaffGroupRequest", output = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/getStaffGroupResponse")
    public TreeParam getStaffGroup(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Long arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns com.viettel.webservice.voffice.RrFileTransferParam
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocumentFile", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.GetDocumentFile")
    @ResponseWrapper(localName = "getDocumentFileResponse", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.GetDocumentFileResponse")
    @Action(input = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/getDocumentFileRequest", output = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/getDocumentFileResponse")
    public RrFileTransferParam getDocumentFile(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "athenticateSSO", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.AthenticateSSO")
    @ResponseWrapper(localName = "athenticateSSOResponse", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.AthenticateSSOResponse")
    @Action(input = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/athenticateSSORequest", output = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/athenticateSSOResponse")
    public String athenticateSSO(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.viettel.webservice.voffice.StaffBO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkAccountSSO", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.CheckAccountSSO")
    @ResponseWrapper(localName = "checkAccountSSOResponse", targetNamespace = "http://service.ws_autosign.voffice.viettel.com/", className = "com.viettel.webservice.voffice.CheckAccountSSOResponse")
    @Action(input = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/checkAccountSSORequest", output = "http://service.ws_autosign.voffice.viettel.com/Vo2AutoSignSystemImpl/checkAccountSSOResponse")
    public List<StaffBO> checkAccountSSO(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
